//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int Id { get; set; }
        public string AlbumTitle { get; set; }
        public string Artist { get; set; }
        public System.DateTime DateReleased { get; set; }
    }
}
